# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./db/ddl/:/ddl
      - ./db/dml/:/dml
      - ./db/scripts/:/scripts
      - ./data/out/:/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  php:
    image: php-bjsztql
    restart: always
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html/
