CREATE TABLE DATA (
    ARTIST VARCHAR(40),
    ALBUM VARCHAR(40),
    RELEASE_DATE DATE,
    TRACK_NUMBER INT,
    SONG VARCHAR(40),
    GENRE VARCHAR(40),
    DURATION INTERVAL
);

CREATE TABLE ACCOUNT_DATA (
    UID INT,
    USER_NAME VARCHAR(40)
);

COPY DATA
FROM '/data/data.csv'
DELIMITER ',' CSV HEADER;

COPY ACCOUNT_DATA
FROM '/data/users.csv'
DELIMITER ',' CSV HEADER;