INSERT INTO ALBUM_ARTIST (ALBUM_ID, ARTIST_ID)
SELECT DISTINCT ALB.ALBUM_ID, ART.ARTIST_ID
FROM ALBUM AS ALB
INNER JOIN DATA AS D
    ON D.ALBUM = ALB.NAME
INNER JOIN ARTIST AS ART
    ON ART.NAME = D.ARTIST
ORDER BY ARTIST_ID;

INSERT INTO ALBUM_GENRE (ALBUM_ID, GENRE_ID)
SELECT DISTINCT ALB.ALBUM_ID, G.GENRE_ID
FROM ALBUM AS ALB
INNER JOIN DATA AS D
    ON D.ALBUM = ALB.NAME
INNER JOIN GENRE G
    ON G.NAME = D.GENRE
ORDER BY ALBUM_ID
