INSERT INTO SONG_GENRE (SONG_ID, GENRE_ID)
SELECT S.SONG_ID, G.GENRE_ID
FROM (
    SELECT ROW_NUMBER() OVER () AS RN, SONG, GENRE
    FROM DATA
) AS D
INNER JOIN SONG AS S
    ON S.SONG_ID = D.RN
INNER JOIN GENRE AS G
    ON G.NAME = D.GENRE;

INSERT INTO SONG_ALBUM (SONG_ID, ALBUM_ID, TRACK_NUMBER) 
SELECT S.SONG_ID, A.ALBUM_ID, ROW_NUMBER() OVER (PARTITION BY A.ALBUM_ID) AS TRACK_NUMBER
FROM (
    SELECT ROW_NUMBER() OVER () AS RN, SONG, ALBUM
    FROM DATA
) AS D
INNER JOIN SONG AS S
    ON S.SONG_ID = D.RN
INNER JOIN ALBUM AS A
    ON A.NAME = D.ALBUM;

INSERT INTO SONG_ARTIST (SONG_ID, ARTIST_ID)
SELECT S.SONG_ID, A.ARTIST_ID
FROM (
    SELECT ROW_NUMBER() OVER () AS RN, SONG, ARTIST
    FROM DATA
) AS D
INNER JOIN SONG AS S
    ON S.SONG_ID = D.RN
INNER JOIN ARTIST AS A
    ON A.NAME = D.ARTIST;
